name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Virtual Environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Install Dependencies
        run: poetry install

      - name: Package
        run: poetry run pyinstaller --clean --noconfirm --log-level WARN cli.spec

      - name: Rename
        run: |
          $tag = $env:GITHUB_REF -replace 'refs/tags/', ''
          Get-ChildItem -Path dist | ForEach-Object {
            Rename-Item -Path $_.FullName -NewName "$tag-$($_.Name)"
          }

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
          generate_release_notes: true
